language: node_js

node_js:
  - "12"

script:
  - echo '******Build Starting...******'
  - echo 'Installing Dependencies'
  - cd resthub
  - npm install
  - echo 'Running Tests'
  - npm test
  - echo '******Build Successful!******'