language: node_js

node_js:
  - "12"

before_script: chmod 0777 ./resthub/node_modules/.bin/mocha

services:
  - mongodb

script:
  - echo '******Build Starting...******'
  - echo 'Installing Dependencies'
  - cd resthub
  - npm install
  - echo 'Running Tests'
  - npm run test
  - echo '******Build Successful!******'